### ISSUE TITLE
Cognito User Pool attribute naming conflict during upgrade from v2.0.0 to v3.3.10

### ISSUE THREAD

**Issue by nishikkr** [aws-solutions/network-orchestration-for-aws-transit-gateway#137]
**Describe the bug**

I notied this when upgrading Network Orchestration for AWS Transit Gateway (formerly STNO) from v2.0.0 to v3.3.10, there's an issue with the Cognito User Pool attribute naming convention. The current template uses a colon (:) in the custom attribute name, which is no longer allowed in some regions due to recent backend changes in Amazon Cognito.

**To Reproduce**

1. Deploy Network Orchestration for AWS Transit Gateway v2.0.0
2. Attempt to upgrade to v3.3.10
3. Observe the error during the creation of the Cognito User Pool

This is how I have done it but, you can simply deploy the lates version and it will still fail 
**Expected behavior**

The upgrade process should complete successfully without any errors related to Cognito User Pool attribute naming.

**Please complete the following information about the solution:**

- [x] Version: v3.3.10
- [x] Region: [Affected regions, e.g., eu-central-2, us-east-1 that I have confirmed]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [x] Were there any errors in the CloudWatch Logs?

**Screenshots**

N/A

**Additional context**

The error occurs in the following part of the CloudFormation template:

```yaml
STNOUserPool:
  Type: AWS::Cognito::UserPool
  Condition: DeployWebUiCondition
  Properties:
    Schema:
      - AttributeDataType: String
        DeveloperOnlyAttribute: false
        Mutable: false
        Name: custom:CognitoUserGr
        Required: false
        StringAttributeConstraints:
          MaxLength: 256
          MinLength: 1
```

The error message received is:

```
[ERROR] InvalidParameterException: An error occurred (InvalidParameterException) when calling the CreateUserPool operation: Entity Type: USER, Message: AttributeName: User.role:v2, DataType: STRING, Error: Attribute names MUST conform to the following rules: _|ALPHA *(nameChar) and nameChar is "$" / "-" / "_" /DIGIT / ALPHA
```

A temporary workaround is to change the attribute name from `custom:CognitoUserGr` to `custom_CognitoUserGr`. However, I would like to know the potential impact of this change on existing deployments and functionality.
